name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pull and Deploy Backend
        run: |
          cd /home/ubuntu/FinHubBack

          echo "Pulling latest code from main..."
          git pull origin main

          echo "Cleaning build cache..."
          rm -rf dist/
          rm -rf node_modules/
          rm -rf .tsbuildinfo
          rm -rf node_modules/.cache/
          rm -rf ~/.npm/_cacache/

          echo "Installing dependencies..."
          npm install

          echo "Pulling DB schema..."
          npx prisma db pull

          echo "Generating Prisma client..."
          npx prisma generate

          echo "Building app with adequate memory..."
          NODE_OPTIONS="--max-old-space-size=2048" npm run build

          echo "Restarting with PM2..."
          pm2 delete finhub-back || true
          pm2 start dist/main.js --name finhub-back --node-args="--max-old-space-size=1024"

          echo "Deployment completed successfully."